AllCops:
  Exclude:
    - bin/*
    - lib/tasks/*.rake
    - Gemfile
    - Rakefile

Documentation:
  Enabled: false

LineLength:
  Max: 103

TrailingComma:
  Enabled: false

TrivialAccessors:
  AllowDSLWriters: true

StringLiterals:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/MethodLength:
  Max: 15
